@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "delete 7"

package snapshots <<rectangle>> {
    class State1 as "<u>s0:Snapshot</u>"
    class State2 as "<u>s1:Snapshot</u>"
    class State3 as "<u>s2:Snapshot</u>"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "snapshotPosition" #FFFFFF

Pointer -up-> State3
@end
