@startuml
!include style.puml
skinparam ArrowFontStyle plain


participant ":Model" as Model MODEL_COLOR

[-> Model : moveSnapshot()
activate Model

Model -> Model : copySnapshot()
activate Model
Model -> Model
deactivate Model

[<-- Model
deactivate Model

@enduml
